name: HA and HACS Validate

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  ha_and_hacs_validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.3
      - name: Hassfest validation
        uses: home-assistant/actions/hassfest@master
      - name: HACS validation
        uses: hacs/action@22.5.0
        with:
          category: integration
          ignore: brands
